package com.act.hospitalmanagementsystem.notification.enums;

public enum NotificationType {
    APPOINTMENT_REMINDER,
    LAB_RESULT,
    PRESCRIPTION_REMINDER,
    SYSTEM_ALERT,
    APPROVAL_NOTIFICATION,
    DOCUMENT_NOTIFICATION,
    EMERGENCY_ALERT,
    BILLING_NOTIFICATION,
    PAYMENT_CONFIRMATION,
    INSURANCE_CLAIM,
    DISCHARGE_SUMMARY,
    FOLLOW_UP_REMINDER,
    MEDICATION_REFILL,
    TEST_RESULT,
    ADMISSION_NOTIFICATION,
    TRANSFER_NOTIFICATION,
    CUSTOM
}
